name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: awdware/dev/.github/workflows/nodejs.yml@main
    secrets: inherit
    with:
      node-versions: '["22.x"]'
